export const bikes = [
    {
        id: '1',
        name: 'M013',
        max_weight:'180 Kg',
        image: 'assets/images/abouelgoukh/bikes/M013-600x600-removebg-preview.png',
        main_category: 'Bike',
        sub_category: 'Spinning Bikes',
        tension: "PAD",
        made_in:'China'
    },
    {
        id: '2',
        name: 'M083',
        max_weight:'100 Kg',
        image: 'assets/images/abouelgoukh/bikes/M083-600x600-removebg-preview.png',
        main_category: 'Bike',
        sub_category: 'Spinning Bikes',
        tension: "PAD",
        made_in:'China'
    },
    {
        id: '3',
        name: 'M023',
        max_weight:'150 Kg',
        image: 'assets/images/abouelgoukh/bikes/M-023-600x600-removebg-preview.png',
        main_category: 'Bike',
        sub_category: 'Spinning Bikes',
        tension: "PAD",
        made_in:'China'
    },
    {
        id: '4',
        name: 'M053',
        max_weight:'130 Kg',
        image: 'assets/images/abouelgoukh/bikes/M053.png',
        main_category: 'Bike',
        sub_category: 'Spinning Bikes',
        tension: "PAD",
        made_in:'China'
    },
    {
        id: '5',
        name: 'Model 1530',
        max_weight:'180 Kg',
        image: 'assets/images/abouelgoukh/bikes/1530-600x600-removebg-preview.png',
        main_category: 'Bike',
        sub_category: 'Spinning Bikes',
        tension: "PAD",
        made_in:'China'
    },
    {
        id: '6',
        name: 'Model 1540',
        max_weight:'180 Kg',
        image: 'assets/images/abouelgoukh/bikes/1540-600x600-removebg-preview.png',
        main_category: 'Bike',
        sub_category: 'Spinning Bikes',
        tension: "PAD",
        made_in:'China'
    },
    {
        id: '7',
        name: 'Model 1550',
        max_weight:'180 Kg',
        image: 'assets/images/abouelgoukh/bikes/1550-600x600.png',
        main_category: 'Bike',
        sub_category: 'Belt Bikes',
        tension: "Belt",
        made_in:'China'
    },
    {
        id: '8',
        name: 'Model Magnetic 1',
        max_weight:'180 Kg',
        image: 'assets/images/abouelgoukh/bikes/mag-1-600x600.png',
        main_category: 'Bike',
        sub_category: 'Magnetic Bikes',
        tension: "Magnetic",
        made_in:'China'
    },
    {
        id: '9',
        name: 'Model Magnetic 2',
        max_weight:'180 Kg',
        image: 'assets/images/abouelgoukh/bikes/mag-2-600x600.png',
        main_category: 'Bike',
        sub_category: 'Magnetic Bikes',
        tension: "Magnetic",
        made_in:'China'
    },
    {
        id: '10',
        name: 'CR800 RECUMBENT BIKE',
        description: 'Durable, comfortable, and smooth are all qualities of the Spirit Fitness CR800 semi-recumbent fitness bike. Easy adjustments, bright LED screens, a turbo cooling fan, high density foam seats, challenging programs, 40 levels of magnetic resistance, and a generator powered console are standard on this model. Indoor exercise bikes have been around for many decades. Their appeal and effectiveness have stood the test of time. Comfort, convenience, familiarity, enjoyment, and medical conditions are a few reasons this modality appeals to a large segment of the population. The entire C series expounds on two of these critical areas – comfort and convenience. We know that if your users don’t enjoy the experience that our products create, they won’t feel compelled to make using them a part of their lifestyle.',
        max_weight:'145 lbs.',
        dimensions:'57 X 30 X 51 in',
        weight_capacity:'450 lbs.',
        heart_rate:'Contact & Telemetric (Chest Strap sold separately)',
        resistance: '40 Levels',
        image: 'assets/images/abouelgoukh/bikes/cr800.png',
        main_category: 'Bike',
        sub_category: 'Commercial Bikes, RECUMBENT BIKES',
        tension: "PAD",
        adjustments: 'You can adjust the seat easily and intuitively by pulling up on the yellow spring loaded handle located directly in front of it.',
        comfort: 'The seat and backrest are made of high durometer foam pads; the pedals are also padded for less stress on your feet.',
        heart_rate_profile:'There is a bar graph integrated into the console that lets you know where your heart rate is in relation to projected maximum (calculated when you enter your age in the programming section of each program).',
        flywheel_sys: 'A heavy duty 30 lb. flywheel results in more inertia (Revolutions Per Minute & Watt output).',
        generator_sys:'This unit uses a generator to power the console. Therefore there is no need for an electrical hookup.',
        made_in:'China'
    },
    {
        id: '11',
        name: 'CU800 UPRIGHT BIKE',
        description: 'Durable, comfortable, and smooth are all qualities of the Spirit Fitness CR800 semi-recumbent fitness bike. Easy adjustments, bright LED screens, a turbo cooling fan, high density foam seats, challenging programs, 40 levels of magnetic resistance, and a generator powered console are standard on this model. Indoor exercise bikes have been around for many decades. Their appeal and effectiveness have stood the test of time. Comfort, convenience, familiarity, enjoyment, and medical conditions are a few reasons this modality appeals to a large segment of the population. The entire C series expounds on two of these critical areas – comfort and convenience. We know that if your users don’t enjoy the experience that our products create, they won’t feel compelled to make using them a part of their lifestyle.',
        sub_category: 'Commercial Bikes, RECUMBENT BIKES',
        image: 'assets/images/abouelgoukh/bikes/cu800_po_md.png',
        max_weight:'115 lbs.',
        dimensions:' 42 X 21 X 53 in',
        weight_capacity:'450 lbs.',
        heart_rate:'Contact & Telemetric (Chest Strap sold separately)',
        resistance: '40 Levels',
        main_category: 'Bike',
        tension: "PAD",
        adjustments: 'You can adjust the seat easily and intuitively by pulling up on the yellow spring loaded handle located directly in front of it.',
        comfort: 'The seat and backrest are made of high durometer foam pads; the pedals are also padded for less stress on your feet.',
        heart_rate_profile:'There is a bar graph integrated into the console that lets you know where your heart rate is in relation to projected maximum (calculated when you enter your age in the programming section of each program).',
        flywheel_sys: 'A heavy duty 30 lb. flywheel results in more inertia (Revolutions Per Minute & Watt output).',
        generator_sys:'This unit uses a generator to power the console. Therefore there is no need for an electrical hookup.',
        made_in:'China'
    },
];