export const helmets = [
    {
        id: '1',
        name: 'ENDURANCE M2',
        description:'The Endurance M2 has a few elements that make it perfect for long rides in the backcountry. It was developed with our 2-layer TC Technology. This means that the shell is made with two layers — a standard EPS foam core and an in-molded polycarbonate shell. The combination of the two makes it lightweight and strong. It covers a bit more of the back of the head than the M1, making it ideal for technical trails. We shape it with 21 vents to maximize airflow for comfort in hot weather, and the front four have mesh installed to keep out the wayward bee or spider as you blaze down the trail. Like our other helmets, the Endurance M1 features Coolmax pads for optimum cushioning and comfort. You’ll also get a removable visor and an easy-to-use ratcheting dial retention system in the back.',
        image: 'assets/images/abouelgoukh/helmets/M2-3-600x518.jpg',
        main_category: 'Helmets',
        orbea_airflow: 'better ventilation and a more compact structure.',
        tc_tech_construction: '2 Layer',
        erc: 'Ergonomic retention system',
        asac: 'Adjustable straps and closure.'
    },
    {
        id: '2',
        name: 'ENDURANCE M1',
        description:'The Endurance M1 is ready for adventure. It was developed with our 2-layer TC Technology. This means that the shell is made with two layers — a standard EPS foam core and an in-molded polycarbonate shell. The combination of the two makes it lightweight and strong. We shape it with 23 generous vents to maximize airflow for comfort in hot weather. Like our other helmets, the Endurance M1 features Coolmax pads for optimum cushioning and comfort. You’ll also get a removable visor and an easy-to-use ratcheting dial retention system in the back.',
        image: 'assets/images/abouelgoukh/helmets/M1-2-600x518.jpg',
        main_category: 'Helmets',
        orbea_airflow: 'better ventilation and a more compact structure.',
        tc_tech_construction: '2 Layer',
        erc: 'Ergonomic retention system',
        asac: 'Adjustable straps and closure.'
    },
    {
        id: '3',
        name: 'H10',
        description:'An inexpensive helmet doesn’t have to be basic. The new H10 is loaded with many of the features of our more expensive helmets, including massive ventilation and subtle style. A low ITP (Internal Touch Point) index means fewer points of contact inside the helmet for maximum comfort and improved ventilation. The low-volume shape of the H10 feels less like a bulky helmet and more like an extension of you. 25 vents keep your head cool and let you feel the wind in your hair while a simple two-layer EPS construction provides more substance and durability for a helmet that can sustain a bit more abuse in the back of the car. Pads and mesh liner wick sweat and keep you cool during long days and are easy to clean. A single wheel adjustment system requires only one hand for adjustment.',
        image: 'assets/images/abouelgoukh/helmets/H10-1-600x518.jpg',
        main_category: 'Helmets',
        orbea_airflow: '· ITP INDEX: MINIMIZES THE INTERNAL POINTS OF CONTACT AND IMPROVES INTERNAL VENTILATION FLOW.',
        orbea_airflow2: '· ES INDEX: 25 VENTILATION HOLES AND A MORE COMPACT STRUCTURE. Tc',
        tc_tech_construction: ' 2-Layer Technology',
        tc_tech_construction2: '· POLYCARBONATE INJECTED IN-MOLD.',
        tc_tech_construction3: '· OUTER EPS SHELL.',
        fit_sys: '· ERGONOMIC RETENTION SYSTEM.',
        fit_sys2: '· MICRO-ADJUSTMENT WITH A SMALL WHEEL ACCESSIBLE WITH A SINGLE HAND.',
        specifications: '· CUSHIONING PADS WITH BREATHABLE MESH FABRIC.',
        specifications2: '· ADJUSTABLE STRAPS AND CLOSURE.',
        specifications3: '· BUCKLE WITH PROTECTIVE FEATURE'
    },
    {
        id: '4',
        name: 'NEW CRUISER',
        description:'• Double upper straps (the most stressful point)',
        description2:'• Lower straps anti-bounce system',
        description3:'• All 6 straps tested at 250 kilos each',
        description4:'• All 6 tempered hooks tested at 350 kilos each',
        description5:'• Steel buckles',
        description6:'• Complete with “last-on” bike blocking safety system',
        description7:'• Doubly safe with extra safety strap fixed to frame',
        description8:'• Quick and easy to fit and remove',
        description9:'• Folds flat for storage.',
        image: 'assets/images/abouelgoukh/helmets/new-cruser-600x400.jpg',
        main_category: 'Bike Carrier',
        product_code: '	305 – 306',
        material: 'steel diam.25',
        color:'black',
        max_num_of_bikes:'3',
        max_indv_bike_weight:'15',
        bike_fitment:'frame',
        max_size_frame_section:'60',
        max_bike_size:'	29″',
        max_width_bike_wheel:'all',
        max_distance_bike_wheel:'all',
        distance_bike_trails:'N/A',
        frame_pro_sys:'ok',
        locking_bike:'no',
        distance_tube:'415',
        product_size:'art.305 80*55*35 art.306 80*50*24',
        product_weight:'art.305 3,95 art.306 3,38',
        packaging:'art.306 shrink wrap art.305 box'
    }
];