

export const NH = [
    {
        id: '1',
        name: 'NH3010D LOW PECTORAL FLY',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/1.jpg',
        dimensions:'1720x1550x1660mm',
        net_weight:'125 Kg',
        gross_weight:'257 Kg',
        standard_load:'75 Kg',
        features:'Pre-stretch foot lever allows control of the start position and aiding in entry and exit of the machine.',
        features2:'Hidden  cams for variable resistance'
    },
    {
        id: '2',
        name: 'NH3010G HIGH PECTORAL FLY',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/2.jpg',
        dimensions:'1980x1960x2000mm',
        net_weight:'214 Kg',
        gross_weight:'235 Kg',
        standard_load:'75 Kg',
        features:'Floating inputs adjust for varied arm lengths.',
        features2:'6 position arm adjustment provides fullrange of motion for both Pectoral Fly and Rear Deltoid movements.',
        features3:'Independent arm resistance ensures equal muscle training',
        features4:'Dual-position handles with angled grips'
    },
    {
        id: '3',
        name: 'NH3011 BICEP CURL',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/3.jpg',
        dimensions:'1740x1100x1660mm',
        net_weight:'198 Kg',
        gross_weight:'211 Kg',
        standard_load:'75 Kg',
        features:'Angled pad fully supports the upper arm to eliminate unwanted shoulder movement.',
        features2:'Cambered handle provides multiple grip positions.'
    },
    {
        id: '4',
        name: 'NH3013 SHOULDER PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/4.jpg',
        dimensions:'1460x1340x1670mm',
        net_weight:'181 Kg',
        gross_weight:'212 Kg',
        standard_load:'75 Kg',
        features:'Long lever action for constant resistance and Biomechanically correct motion.',
        features2:'Angled dual-position handgrip for proper ergonomic fit and exercise variation.'
    },
    {
        id: '5',
        name: 'NH3015 CABLE CROSSOVER',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/5.jpg',
        dimensions:'4330x1210x2320mm',
        net_weight:'374 Kg',
        gross_weight:'425 Kg',
        standard_load:'75 Kg',
        features:'11-position adjustable dual-pulley system.',
        features2:'Variable height pulley adjustment for numerous workout positions and exercises.',
        features3:'Multi-grip chin-up bar mounted on overhead crossbeam.'
    },
    {
        id: '6',
        name: 'NH3017 LEG EXTENSION',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/6.jpg',
        dimensions:'1730x1110x1660mm',
        net_weight:'209 Kg',
        gross_weight:'248 Kg',
        standard_load:'75 Kg',
        features:'7 position back pad angled at 30º and seat pad angled at 20º for complete range of motion.',
        features2:'Multiple start position adjustments.',
        features3:'Ergonomically located handles with contoured grips for proper user alignment during exercise',
        features4:'Adjustable foot roll design to accommodate various leg lengths.',
    },
    {
        id: '7',
        name: 'NH3018 AB/BACK EXTENSION',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/7.jpg',
        dimensions:'1460x1100x1670mm',
        net_weight:'229 Kg',
        gross_weight:'245 Kg',
        standard_load:'100 Kg',
        features:'6 position range of motion adjustment allows users to easily change between Low Back and Abdominal exercises.',
        features2:'Dual function adjustable roller pad for comfort in use and proper alignment for both ab and back exercises.',
        features3:'Dual non-slip foot positions accommodate a wide range of users while providing support during exercise',
    },
    {
        id: '8',
        name: 'NH3019 LEG PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/8.jpg',
        dimensions:'1950x1210x1670mm',
        net_weight:'243 Kg',
        gross_weight:'265 Kg',
        standard_load:'100 Kg',
        features:'Low profile design and ergonomically positioned handles for easy entry and exit.',
        features2:'Contoured back pad provides low back support throughout the entire range of motion.',
        features3:'Oversize, non-skid foot platform for exercise variation',
    },
    {
        id: '9',
        name: 'NH3020A HIGH/LOW LAT PULLDOWN',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/9.jpg',
        dimensions:'1780x1360x2230mm',
        net_weight:'234 Kg',
        gross_weight:'255 Kg',
        standard_load:'100 Kg',
        features:'Adjustable thigh hold-down pads offer stability during exercise and provide a firm support for maximum weight usage.',
        features2:'Foot rest bars provide support and encourage proper alignment during Seated Row movement.',
        features3:'No cable change featuring each individual station with its own attachment and set-up.',
        features4:'Rubber coated lat bar and row handle for comfort.',
    },
    {
        id: '10',
        name: 'NH3021 PRONE LEG CURL',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/10.jpg',
        dimensions:'1770x1120x1670mm',
        net_weight:'200 Kg',
        gross_weight:'214 Kg',
        standard_load:'75 Kg',
        features:'Angled bench between hip and chest pads  helps reduce low back stress and unwanted knee forces.',
        features2:'Multiple start position adjustments.',
        features3:'Dual hand-grips add stability and balance.',
        features4:'Adjustable foot roll design to accommodate various leg lengths.',
    },
    {
        id: '11',
        name: 'NH3023 CHEST PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/11.jpg',
        dimensions:'1480x1420x1670mm',
        net_weight:'171 Kg',
        gross_weight:'220 Kg',
        standard_load:'75 Kg',
        features:'Pre-stretch foot lever allows control of the start position and aiding in entry and exit of the machine.',
        features2:'Dual handle positions for variation of exercises.',
    },
    {
        id: '12',
        name: 'NH3024 SEATED ROW',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/12.jpg',
        dimensions:'1610x1180x1670mm',
        net_weight:'189 Kg',
        gross_weight:'235 Kg',
        standard_load:'100 Kg',
        features:'360° rotatable hand grips for different training positions.'
    },
    {
        id: '13',
        name: 'NH3027 OUTER/INNER THIGH',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/13.jpg',
        dimensions:'1640x1600x1660mm',
        net_weight:'203 Kg',
        gross_weight:'224 Kg',
        standard_load:'75 Kg',
        features:'Dual functionality of hip abduction and hip adduction in one machine saves valuable floor space.',
        features2:'Forward weight stack serves as privacy shield.',
        features3:'Dual foot bars accommodate a broad range of user heights.',
        features4:'Conveniently located lever adjustment for the start positions for both exercises.'
    },
    {
        id: '14',
        name: 'NH3028 ASSISTED CHIN/DIP',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/14.jpg',
        dimensions:'1220x1300x2210mm',
        net_weight:'237 Kg',
        gross_weight:'258 Kg',
        standard_load:'75 Kg',
        features:'Multi position handles facilitate a variety of users.',
        features2:'Fold-away upholstered knee platform for assisted or unassisted exercise.',
        features3:'Platform travels on linear bearings system for smoother, quieter operation and longer life.',
    },
    {
        id: '15',
        name: 'NH3028 ASSISTED CHIN/DIP',
        main_category: 'Gym Equipment',
        sub_category: 'NH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NH/15.jpg',
        dimensions:'1830x1070x1660mm',
        net_weight:'196 Kg',
        gross_weight:'215 Kg',
        standard_load:'75 Kg',
        features:'Pivoting handle accommodates users of different sizes',
        features2:'Arm and seat pads are angled to provide maximum stability',
    },
  ];
  
  export const NC = [
    {
        id: '1',
        name: 'NC2010D LOW PECTORAL FLY',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/1.jpg',
        dimensions:'1440x1030x1605mm',
        net_weight:'195 Kg',
        gross_weight:'225 Kg',
        standard_load:'75 Kg',
        features:'Adjustable starting position.',
        features2:'Hidden  cams for variable resistance'
    },
    {
        id: '2',
        name: 'NC2010G HIGH PECTORAL FLY',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/2.jpg',
        dimensions:'2020x1510x1985mm',
        net_weight:'230 Kg',
        gross_weight:'251 Kg',
        standard_load:'75 Kg',
        features:'6 position arm adjustment provides fullrange of motion for both Pectoral Fly and Rear Deltoid movements.',
        features2:'Independent arm resistance ensures equal muscle training',
        features3:'Dual-position handles with angled grips'
    },
    {
        id: '3',
        name: 'NC2011 BICEP CURL',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/3.jpg',
        dimensions:'1405x1065x1605mm',
        net_weight:'180 Kg',
        gross_weight:'197 Kg',
        standard_load:'75 Kg',
        features:'Angled pad fully supports the upper arm to eliminate unwanted shoulder movement.',
        features2:'Cambered handle provides multiple grip positions.'
    },
    {
        id: '4',
        name: 'NC2013 SHOULDER PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/4.jpg',
        dimensions:'1460x1340x1670mm',
        net_weight:'143 Kg',
        gross_weight:'198 Kg',
        standard_load:'75 Kg',
        features:'Long lever action for constant resistance and Biomechanically correct motion.',
        features2:'Angled dual-position handgrip for proper ergonomic fit and exercise variation.'
    },
    {
        id: '5',
        name: 'NC2015 CABLE CROSSOVER',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/5.jpg',
        dimensions:'4140x1150x2310mm',
        net_weight:'369 Kg',
        gross_weight:'366 Kg',
        standard_load:'75 Kg',
        features:'15-position adjustable dual-pulley system.',
        features2:'Variable height pulley adjustment for numerous workout positions and exercises.',
        features3:'Multi-grip chin-up bar mounted on overhead crossbeam.'
    },
    {
        id: '6',
        name: 'NC2017 LEG EXTENSION',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/6.jpg',
        dimensions:'1605x1095x1605mm',
        net_weight:'195 Kg',
        gross_weight:'239 Kg',
        standard_load:'100 Kg',
        features:'7 position back pad angled at 30º and seat pad angled at 20º for complete range of motion.',
        features2:'Multiple start position adjustments.',
        features3:'Ergonomically located handles with contoured grips for proper user alignment during exercise',
        features4:'Adjustable foot roll design to accommodate various leg lengths.',
    },
    {
        id: '7',
        name: 'NC2018 AB/BACK EXTENSION',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/7.jpg',
        dimensions:'1425x1065x1605mm',
        net_weight:'220 Kg',
        gross_weight:'227 Kg',
        standard_load:'100 Kg',
        features:'6 position range of motion adjustment allows users to easily change between Low Back and Abdominal exercises.',
        features2:'Dual function adjustable roller pad for comfort in use and proper alignment for both ab and back exercises.',
        features3:'Dual non-slip foot positions accommodate a wide range of users while providing support during exercise',
    },
    {
        id: '8',
        name: 'NC2019 LEG PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/8.jpg',
        dimensions:'2025x1130x1605mm',
        net_weight:'232 Kg',
        gross_weight:'252 Kg',
        standard_load:'100 Kg',
        features:'Low profile design and ergonomically positioned handles for easy entry and exit.',
        features2:'Contoured back pad provides low back support throughout the entire range of motion.',
        features3:'Oversize, non-skid foot platform for exercise variation',
    },
    {
        id: '9',
        name: 'NC2020A HIGH/LOW LAT PULLDOWN',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/9.jpg',
        dimensions:'1890x1500x2250mm',
        net_weight:'223 Kg',
        gross_weight:'248 Kg',
        standard_load:'100 Kg',
        features:'Adjustable thigh hold-down pads offer stability during exercise and provide a firm support for maximum weight usage.',
        features2:'Foot rest bars provide support and encourage proper alignment during Seated Row movement.',
        features3:'No cable change featuring each individual station with its own attachment and set-up.',
        features4:'Rubber coated lat bar and row handle for comfort.',
    },
    {
        id: '10',
        name: 'NH3021 PRONE LEG CURL',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/10.jpg',
        dimensions:'1555x1070x1605mm',
        net_weight:'186 Kg',
        gross_weight:'205 Kg',
        standard_load:'75 Kg',
        features:'Angled bench between hip and chest pads  helps reduce low back stress and unwanted knee forces.',
        features2:'Multiple start position adjustments.',
        features3:'Dual hand-grips add stability and balance.',
        features4:'Adjustable foot roll design to accommodate various leg lengths.',
    },
    {
        id: '11',
        name: 'NC2023 CHEST PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/11.jpg',
        dimensions:'980x1420x1605mm',
        net_weight:'188 Kg',
        gross_weight:'209 Kg',
        standard_load:'75 Kg',
        features:'Press arm offers both traditional and neutral hand grip positions for exercise variation.',
    },
    {
        id: '12',
        name: 'NC2024 SEATED ROW',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/12.jpg',
        dimensions:'1610x1180x1670mm',
        net_weight:'165 Kg',
        gross_weight:'221 Kg',
        standard_load:'100 Kg',
        features:'5 position seat and 8 position chest pad with custom fitted sleeve inserts for stable,low friction adjustments.',
        features:'Angled dual-position handgrip for properergonomic fit and exercise variation.'
    },
    {
        id: '13',
        name: 'NC2027 OUTER/INNER THIGH',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/13.jpg',
        dimensions:'1715x1575x1605mm',
        net_weight:'195 Kg',
        gross_weight:'227 Kg',
        standard_load:'75 Kg',
        features:'Dual functionality of hip abduction and hip adduction in one machine saves valuable floor space.',
        features2:'Forward weight stack serves as privacy shield.',
        features3:'Dual foot bars accommodate a broad range of user heights.',
        features4:'Conveniently located lever adjustment for the start positions for both exercises.'
    },
    {
        id: '14',
        name: 'NC2028 ASSISTED CHIN/DIP',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/14.jpg',
        dimensions:'1295x1200x2360mm',
        net_weight:'215 Kg',
        gross_weight:'240 Kg',
        standard_load:'75 Kg',
        features:'Multi position handles facilitate a variety of users.',
        features2:'Fold-away upholstered knee platform for assisted or unassisted exercise.',
        features3:'Platform travels on linear bearings system for smoother, quieter operation and longer life.',
    },
    {
        id: '15',
        name: 'NC2030 TRICEP EXTENSION',
        main_category: 'Gym Equipment',
        sub_category: 'NC SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/NC/15.jpg',
        dimensions:'1500x1065x1605mm',
        net_weight:'180 Kg',
        gross_weight:'203 Kg',
        standard_load:'75 Kg',
        features:'Pivoting handle accommodates users of different sizes',
        features2:'Arm and seat pads are angled to provide maximum stability',
    },
  ];
  
  export const TH = [
    {
        id: '1',
        name: 'TH9900 5-STACK JUNGLE GYM',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/1.jpg',
        dimensions:'4310×3390×2310mm',
        net_weight:'686 Kg',
        gross_weight:'817 Kg',
        standard_load:'150lbs X3+200lbs X2',
        description:'The TH9900 5-Station jungle gym is an exceptional multi-function unit. It is made up of an adjustable cable crossover, a low row, a lat pull down,a triceps push-down station and a chinning bar. Perfect for all commercial gyms and professional training facilities, this space saving machine offers multiple training programs and exercises.',
        features:'17-position cable-crossover.',
        features2:'Lat pull-down stations with thigh hold-down pads.',
        features3:'Seated low row station with foot plate.',
        features4:'Two end stations with high/low pulley system.',
        features5:'Triceps pushdown station.',
        features6:'Multi-grip chin-up bar.',
    },
    {
        id: '2',
        name: 'TH9901 8-STACK JUNGLE GYM',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/2.jpg',
        dimensions:'(L)4780×(W)3390×(H)2310mm',
        net_weight:'1110 Kg',
        gross_weight:'1199 Kg',
        standard_load:'200lbs x4+150lbs x4',
        description:'The TH9901 8-Station jungle gym is an exceptional multi-function unit. It is made up of 1 adjustable cable crossover, 2 low rows, 2 lat pull downs,2 triceps push-down stations and a chinning bar. Perfect for all commercial gyms and professional training facilities, this space saving machine offers multiple training programs and exercises.',
        features:'17-position cable-crossover.',
        features2:'2 Lat pull-down stations with thigh hold-down rollers.',
        features3:'2 Seated low row stations with foot plate.',
        features4:'2 Triceps push-down stations.',
        features5:'Multi-grip chin-up bar',
    },
    {
        id: '3',
        name: 'TH9910G HIGH PECTORAL FLY',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/3.jpg',
        dimensions:'1320×1180×1870mm',
        net_weight:'240 Kg',
        gross_weight:'259 Kg',
        standard_load:'200lbs',
        features:'Floating inputs adjust for varied arm lengths.',
        features2:'Multiple start positions adjustment.',
        features3:'Pneumatically assisted seat height adjustment.'
    },
    {
        id: '4',
        name: 'TH9911 BICEP CURL',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/4.jpg',
        dimensions:'1150×1070×1640mm',
        net_weight:'192 Kg',
        gross_weight:'211 Kg',
        standard_load:'150lbs',
        features:'Angled pad fully supports the upper arm to eliminate unwanted shoulder movement.',
        features2:'Cambered handle provides multiple grip positions.',
        features3:'Pneumatically assisted seat height adjustment.'
    },
    {
        id: '5',
        name: 'TH9913 SHOULDER PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/5.jpg',
        dimensions:'1470×1090×1640mm',
        net_weight:'174 Kg',
        gross_weight:'194 Kg',
        standard_load:'200lbs',
        features:'Independent converging movement provides a natural path of motion .',
        features2:'Counterbalanced pressing arm for optimized starting resistance.',
        features3:'Dual grips provide a barbell grip as well as neutral grip favorable for individuals with compromised shoulders.',
        features4:'Oversized handgrips provide greater comfort and variety .',
        features5:'Pneumatically assisted seat height adjustment.',
    },
    {
        id: '6',
        name: 'TH9915 CABLE CROSSOVER',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/6.jpg',
        dimensions:'3660×1000×2260mm',
        net_weight:'410 Kg',
        gross_weight:'419 Kg',
        standard_load:'150lbs X2',
        features:'Fully adjustable high/low cable pulley system with a pivot range of 180°.',
        features2:'Independent, designed for unilateral or bilateral movement .',
        features3:'Built-in wide and narrow grip chin-up bar.',
    },
    {
        id: '7',
        name: 'TH9917 LEG EXTENSION',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/7.jpg',
        dimensions:'1190×1070×1640mm',
        net_weight:'242 Kg',
        gross_weight:'261 Kg',
        standard_load:'200lbs',
        features:'5 position back pad with gas spring assist angled 95°and seat pad angled 20°for proper ergonomic function and user comfort.Easily adjustable from the seated position.',
        features2:'Ergonomically located handles for proper user alignment during exercise.',
    },
    {
        id: '8',
        name: 'TH9918 LOW BACK/ABDOMINAL',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/8.jpg',
        dimensions:'1340×980×1640mm',
        net_weight:'220 Kg',
        gross_weight:'243 Kg',
        standard_load:'200lbs',
        features:'Dual function adjustable roller pad for comfort in use and proper alignment for both ab and back exercises.   ',
        features2:'Counter balanced resistance arm with 5 adjustable starting points.',
    },
    {
        id: '9',
        name: 'TH9919 LEG PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/9.jpg',
        dimensions:'(L)2040×(W)1110×(H)1840mm',
        net_weight:'311 Kg',
        gross_weight:'325 Kg',
        standard_load:'200lbs',
        features:'Large rubber footplate permits a variety of foot positions for different exercises including calf training.',
        features2:'Convenient control pin easily adjusts trolley for various starting positions.',
    },
    {
        id: '10',
        name: 'TH9920 LAT PULLDOWN',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/10.jpg',
        dimensions:'1400×1250×2160mm',
        net_weight:'210 Kg',
        gross_weight:'230 Kg',
        standard_load:'200lbs',
        features:'Forward aligned pulley encourages correct form.',
        features2:'Adjustable thigh rollere accommodate users of all sizes.',
    },
    {
        id: '11',
        name: 'TH9921A PRONE LEG CURL',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/11.jpg',
        dimensions:'1485×1020×1640mm',
        net_weight:'227 Kg',
        gross_weight:'249 Kg',
        standard_load:'200lbs',
        features:'Angled bench between hip and chest pads helps reduce low back stress and unwanted knee forces.',
        features2:'Dual hand-grips add stability and balance.',
        features3:'Adjustable foot roll design to accommodate various leg lengths.',
    },
    {
        id: '12',
        name: 'TH9923 CHEST PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/15.jpg',
        dimensions:'1450×1340×1700mm',
        net_weight:'234 Kg',
        gross_weight:'263 Kg',
        standard_load:'200lbs',
        features:'Dual grips provide a barbell grip as well as neutral grip favorable for individuals with compromised shoulders.',
        features2:'The dual pivot provides a natural path of motion. .',
        features3:'Pneumatically assisted seat height adjustment.',
    },
    {
        id: '13',
        name: 'TH9924 MID-ROW',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/13.jpg',
        dimensions:'1270×1190×1640mm',
        net_weight:'221 Kg',
        gross_weight:'238 Kg',
        standard_load:'200lbs',
        features:'360ºfully articulating U-Grip handles allow user defined hand positioning and path of motion',
        features2:'The dual pivot provides a natural path of motion.',
        features3:'Pneumatically assisted seat height adjustment.',
    },
    {
        id: '14',
        name: 'TH9927 INNER /OUTER THIGH',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/14.jpg',
        dimensions:'1450×1500×1640mm',
        net_weight:'239 Kg',
        gross_weight:'257 Kg',
        standard_load:'200lbs',
        features:'Dual functionality of hip abduction and hip adduction in one machine saves valuable floor space.',
        features2:'Forward weight stack serves as privacy shield.',
        features3:'Dual foot bars accommodate a broad range of user heights.',
        features4:'Conveniently located lever adjustment for start positions for both exercises.',
    },
    {
        id: '15',
        name: 'TH9928 ASSISTED CHIN/DIP',
        main_category: 'Gym Equipment',
        sub_category: 'TH SELECTORIZED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH/15.jpg',
        dimensions:'1370×1090×2290mm',
        net_weight:'243 Kg',
        gross_weight:'276 Kg',
        standard_load:'200lbs',
        features:'Multi position handles facilitate a variety of users.',
        features2:'Fold-away upholstered knee platform for assisted or unassisted exercise.',
        features3:'Platform travels on linear bearings system for smoother, quieter operation and longer life.',
    },
  ];
  export const TH_PT = [
    {
        id: '1',
        name: 'PT6731 AB.CRUNCH',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT/1.jpg',
        dimensions:'1270×1400×1700mm',
        net_weight:'89 Kg',
        gross_weight:'97 Kg',
    },
    {
        id: '2',
        name: 'PT6742 INCLINE ROW',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT/2.jpg',
        dimensions:'2100×880×1250mm',
        net_weight:'85 Kg',
        gross_weight:'93 Kg',
        standard_load:'200lbs x4+150lbs x4',
        description:'The chest pad, non-skid foot plate  featured on the Incline Lever Row stabilize and support the user during the exercise. Rotatable  handles allow users to fine-tune the exercise position, enhancing the workout',
    },
    {
        id: '3',
        name: 'PT6745 LEG EXTENSION',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT/3.jpg',
        dimensions:'(L)1725×(W)1130×(H)1200mm',
        net_weight:'85 Kg',
        gross_weight:'95 Kg',
        features:'Declined seat and back angle offers optimal workout position.',
        features2:'Conveniently placed handle bars for additional stability and performance.',
        features3:'Independant motion for optimising the user experience.'
    },
    {
        id: '4',
        name: 'TH9946D LEG PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT/4.jpg',
        dimensions:'2100×1450×1500mm',
        net_weight:'165 Kg',
        gross_weight:'225 Kg',
        features:'Footplate handle provides easy access on and off the machine',
        features2:'Large footplate to accommodate of variety of exercise positions.',
        features3:'Linkage system design to reduce knee tension.'
    },
    {
        id: '5',
        name: 'TH9946S HACK SQUAT',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT/5.jpg',
        dimensions:'2080×1440×1500mm',
        net_weight:'160 Kg',
        gross_weight:'220 Kg'
    },
    {
        id: '6',
        name: 'TH9947 SMITH MACHINE',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT/6.jpg',
        dimensions:'2130×1470×2260mm',
        net_weight:'210 Kg',
        gross_weight:'200 Kg',
        features:'7-degree bar angle follows the natural free weight path of movement for pressing or squating.',
        features2:'Fully enclosed linear bearings with unsupported  guide rods .',
        features3:'Counter weight inside eliminates shrouds.',
        features4:'Heavy duty adjustable safeties.',
    },
  ];
  
  export const TH_PT_FREE = [
    {
        id: '1',
        name: 'PT6642 POWER RACK',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/1.jpg',
        dimensions:'1300×1050×2100mm',
        net_weight:'130 Kg',
        gross_weight:'140 Kg'
    },
    {
        id: '2',
        name: 'PT6648 WEIGHT HOLDER',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/2.jpg',
        dimensions:'860×860×1260mm',
        net_weight:'60 Kg',
        gross_weight:'65 Kg',
        features:'Holds 10 straight or EZ curl barbells',
        features2:'Molded, bolted on non-skid rubber feet.',
    },
    {
        id: '3',
        name: 'PT6649 TWIST',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/3.jpg',
        dimensions:'1530×660×1200mm',
        net_weight:'43 Kg',
        gross_weight:'51 Kg',
    },
    {
        id: '4',
        name: 'PT6660 BODY STRETCHER',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/4.jpg',
        dimensions:'1355×560×950mm',
        net_weight:'33 Kg',
        gross_weight:'40 Kg',
        features:'Secure footholds to assist stability',
        features2:'Comfortable padded seat and upper body rest',
        features3:'Handles and arm rests promote smooth movement across the full range of motion.'
    },
    {
        id: '5',
        name: 'PT6661 ABDOMINAL BOARD',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/5.jpg',
        dimensions:'1780×800×1020mm',
        net_weight:'61 Kg',
        gross_weight:'61 Kg',
        features:'Secure footholds to assist stability.',
        features2:'Comfortable padded seat and upper body rest.',
        features3:'Large range of motion helps to target upper, lower, mid abdominals and obliques.',
        features4:'Oversized handgrips provide greater comfort and variety .',
        features5:'Handles and arm rests promote smooth movement across the full range of motion.',
    },
    {
        id: '6',
        name: 'PT6675 SQUAT RACK',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/6.jpg',
        dimensions:'1535×1720×1750mm',
        net_weight:'88 Kg',
        gross_weight:'96 Kg',
        features:'The Multi Squat Rack provides one multi-use weight lifting centre.',
        features2:'Combined with the Adjustable Incline Bench,this rack can be used to replicate any workout and the adjustable safety drop-outs ensure safety is paramount.',
    },
    {
        id: '7',
        name: 'PT6677A VERTICAL KNEE RAISER/DIP',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/7.jpg',
        dimensions:'1180×1100×2285mm',
        net_weight:'98 Kg',
        gross_weight:'108 Kg',
        features:'Three body weight exercises in one, space-efficient unit.',
        features2:'Multiple pull-up grip angles offer variety and comfort.',
        features3:'Contoured elbow pads and oversized dip handles provide added comfort',
        features4:'Aluminum alloy guards protect frame from paint chips and scratches.',
    },
    {
        id: '8',
        name: 'TH9940 FLAT BENCH',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/8.jpg',
        dimensions:'1480×550×470mm',
        net_weight:'22 Kg',
        gross_weight:'35 Kg',
        features:'Designed for dumbbell workout and general exercise usage. ',
        features2:'Compact and light weight.',
    },
    {
        id: '9',
        name: 'TH9941 SEATED ARM CURL',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/9.jpg',
        dimensions:'900×890×910mm',
        net_weight:'40 Kg',
        gross_weight:'60 Kg',
        features:'Enhanced angle for maximum bicepsextension as preferred by professional body builders.',
    },
    {
        id: '10',
        name: 'TH9942 OLYMPIC FLAT BENCH',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/10.jpg',
        dimensions:'2060×1280×1200mm',
        net_weight:'75 Kg',
        gross_weight:'88 Kg',
        features:'The classic bench press redefined. Ergonomically designed with both the user and the spotter in mind.',
        features2:'The Olympic Horizontal Bench Press is one of the safest and most effective on the market.',
    },
    {
        id: '11',
        name: 'TH9943 OLYMPIC INCLINE BENCH',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/11.jpg',
        dimensions:'1970×1290×1140mm',
        net_weight:'80 Kg',
        gross_weight:'88 Kg',
        features:'Adjustable seat pad to facilitate foot support  for maximum performance and stability.',
        features2:'Built-in spotter platform.',
        features3:'As a variation on the standard bench press IMPACT has developed the Olympic Incline Bench Press allowing the user to focus on a variety of muscles with the confidence of stability and safety as standard.',
    },
    {
        id: '12',
        name: 'TH9943L 2 TIERS DUMBBELL RACK（6 PAIRS）',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/12.png',
        dimensions:'(L)1325×(W)650×(H)840mm',
        net_weight:'48 Kg',
        gross_weight:'56 Kg',
        features:'Offset angle prevent wrist strain.',
        features2:'Individual dumbbell cradles improve safety.',
        features3:'Holds 6 pairs of dumbbells.',
    },
    {
        id: '13',
        name: 'TH9943M 2 TIERS DUMBBELL RACK',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/13.jpg',
        dimensions:'2650×650×840mm',
        net_weight:'82 Kg',
        gross_weight:'91 Kg',
        features:'Offset angle prevent wrist strain.',
        features2:'Individual dumbbell cradles improve safety.',
        features3:'Holds 10 pairs of dumbbells.',
    },
    {
        id: '14',
        name: 'TH9944 OLYMPIC DECLINE BENCH',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/14.jpg',
        dimensions:'1970×1290×1140mm',
        net_weight:'80 Kg',
        gross_weight:'88 Kg',
        features:'High resistant wear surfaces on the bar holder protect frame finish.',
    },
    {
        id: '15',
        name: 'TH9952 ADJUSTABLE SIT-UP BENCH',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/15.jpg',
        dimensions:'1610×650×1100mm',
        net_weight:'65 Kg',
        gross_weight:'73 Kg',
        features:'Variable angle height adjustment .',
        features2:'Built-in handle for proper body alignment at start position.',
    },
    {
        id: '16',
        name: 'TH9953 MULTI-PURPOSE BENCH',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/16.jpg',
        dimensions:'(L)1500×(W)700×(H)1300mm',
        net_weight:'34 Kg',
        gross_weight:'42 Kg',
        features:'Designed for many bench exercises-high level of adjustablitlity from decline to full upright position.',
        features2:'Built-in handle and wheels for easy roll-away.',
    },
    {
        id: '17',
        name: 'TH9970 UTILITY BENCH',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/17.jpg',
        dimensions:'885×590×915mm',
        net_weight:'22 Kg',
        gross_weight:'26 Kg',
        features:'The utility bench has been designed to accommodate all sizes and weights of user whilst providing a stable and safe bench, capable of withstanding the rigours of everyday use.',
    },
    {
        id: '18',
        name: 'TH9971 OLYMPIC PLATE TREE',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/18.jpg',
        dimensions:'910×910×800mm',
        net_weight:'24 Kg',
        gross_weight:'32 Kg',
        features:'Six chrome-coated storage pegs for Olympic.',
        features2:'Plate with a 1000-lb. Capacity.',
    },
    {
        id: '19',
        name: 'TH9972A 45° HYPER EXTENSION',
        main_category: 'Gym Equipment',
        sub_category: 'TH/PT FREE WEIGHT',
        image: 'assets/images/abouelgoukh/gym_equipments/TH_PT_FREE/19.jpg',
        dimensions:'(L)1500×(W)960×(H)850mm',
        net_weight:'49 Kg',
        gross_weight:'54 Kg',
        features:'Low foot position provide safe entry/exit.' ,
        features2:'The support pads and stabilization handles adjust to individual flexibility.',
        features3:'Lower roller support provides stabilization and comfort throughout exercise',
    },
  
  ];
  
  export const SM_CT = [
    {
        id: '1',
        name: 'SM700 SMITH MACHINE',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/1.jpg',
        dimensions:'1290×2310×2160mm',
        net_weight:'195 Kg',
        gross_weight:'200 Kg',
        features:'Bar is counter-balanced for 0 lb. start position.',
        features2:'Ø25mm linear bearing guidance system at 90° travel path.',
        features3:'Adjustable safety hooks and heavy duty recoil safety springs.',
        features4:'Walk-through design.',
        features5:'Built-in weight storage.',
    },
    {
        id: '2',
        name: 'SM715 SHOULDER PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/2.jpg',
        dimensions:'1370×1180×1410mm',
        net_weight:'75 Kg',
        gross_weight:'82 Kg',
        features:'Unilateral movement.',
        features2:'Choice of handles for variations of shoulder presses.',
        features3:'Standard weight horns allow for plate storage',
    },
    {
        id: '3',
        name: 'SM755 SEATED CALF',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/3.jpg',
        dimensions:'1320x820x1080mm',
        net_weight:'53 Kg',
        gross_weight:'63 Kg',
        features:'Machine design emphasizes the Soleus muscle.',
        features2:'Adjustable thigh support device accommodate most users of all sizes.',
        features3:'Conveniently located vertical holder/release bar.',
    },
    {
        id: '4',
        name: 'SM760 LEG PRESS 45-DEGREE',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/4.jpg',
        dimensions:'2630×1550×1510mm',
        net_weight:'167 Kg',
        gross_weight:'186 Kg'
    },
    {
        id: '5',
        name: 'SM770 TIBIA DORSI FLEXION',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/5.png',
        dimensions:'1060x450x360mm',
        net_weight:'25 Kg',
        gross_weight:'31 Kg',
        features:'Machine design allows exercise of the Tibialis Anterior.',
        features2:'Seated position loads the resistance through the hips as opposed to through the spine.',
    },
    {
        id: '6',
        name: 'SM775 ISO-LATERRAL LOW ROW',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/6.png',
        dimensions:'(L)1550×(W)1200×(H)1740mm',
        net_weight:'130 Kg',
        gross_weight:'140 Kg',
        features:'Path of motion is opposite of the Iso-Lateral Decline Press allowing for real push/pull exercise.',
        features2:'Additional handle provided to allow user stabilization during one-arm exercises.',
        features3:'Iso-Lateral motion allows for equal strength development.',
        features4:'Standard weight horns allow for plate storage.',
    },
    {
        id: '7',
        name: 'SM776 ISO-LATERAL HIGH ROW',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/7.png',
        dimensions:':(L)1640×(W)1300×(H)2100mm',
        net_weight:'130 Kg',
        gross_weight:'140 Kg',
        features:'Path of motion is opposite of the Iso-Lateral Decline Press allowing for real push/pull exercise.',
        features2:'Additional handle provided to allow user stabilization during one-arm exercises.',
        features3:'Iso-Lateral motion allows for equal strength development.',
        features4:'Unique path of motion is difficult to replicate using traditional free weights or pulley exercises.',
    },
    {
        id: '8',
        name: 'SM780 BENCH PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/8.jpg',
        dimensions:'1250×1500×1750mm',
        net_weight:'106 Kg',
        gross_weight:'116 Kg',
        features:'The Plate-Loaded Iso-Lateral Bench Press features separate weight horns that provide independent diverging and converging motions for equal strength development.',
        features3:'Upright position allows for easy entry and exit',
        features2:'Iso-Lateral motion allows for equal strength development.',
        features4:'Standard weight horns allow for plate storage.',
    },  
    {
        id: '9',
        name: 'SM781 LOW ROW',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/9.jpg',
        dimensions:'1380×1420×1950mm',
        net_weight:'123 Kg',
        gross_weight:'133 Kg',
        features:'Underhand grip position combined with overhead pivot dictates a natural arc of movement around shoulder joint.',
        features2:'Seat and chest pad are angled slightly to enhance stabilization.',
        features3:'Additional handle provided to allow user stabilization during one-arm exercises.',
        features4:'Standard weight horns allow for plate storage',
    },
    {
        id: '10',
        name: 'SM783 ROWING',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/10.jpg',
        dimensions:'1550×1350×1230mm',
        net_weight:'86 Kg',
        gross_weight:'96 Kg',
        features:'Compact, low-profile design',
        features2:'Multiple grips allow different options for exercise variety.',
        features3:'Additional handle provided to allow user stabilization during one-arm exercise.',
    },
    {
        id: '11',
        name: 'SM784 SEATED DIP',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/11.jpg',
        dimensions:'1900×1450×1050mm',
        net_weight:'95 Kg',
        gross_weight:'105 Kg',
        features:'Allows user to perform exercise either facing in or out.',
        features2:'Excellent exercise for traditional weightlifting while promoting functional training as the exercise replicates exiting a seated position.',
        features3:'Standard weight horns allow for plate storage',
    },
    {
        id: '12',
        name: 'SM785 LATERAL RAISE',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/12.jpg',
        dimensions:'1250×820×1400mm',
        net_weight:'78 Kg',
        gross_weight:'88 Kg'
    },
    {
        id: '13',
        name: 'SM786 HORIZONTAL PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/13.jpg',
        dimensions:'1870×1800×1310mm',
        net_weight:'110 Kg',
        gross_weight:'120 Kg',
        features:'Iso-Lateral version of a traditional bench press.',
        features2:'Replicates biomechanical movements.',
        features3:'Short, direct transmission of resistance.',
        features4:'Standard weight horns allow for plate storage.',
        features5:'Smooth performance and premium durability.',
        features6:'Back pad is angled 5 degrees allowing for better stabilization during heavy lifts.',
        features7:'Iso-Lateral technology: Smooth converging and diverging arcs of motion.',
    },
    {
        id: '14',
        name: 'SM787 DECLINE PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/14.jpg',
        dimensions:'1930×1190×1750mm',
        net_weight:'145 Kg',
        gross_weight:'155 Kg',
        features:'Higher degree of converging motion than the Decline Press.',
        features2:'Start position is wider making it more applicable for larger users.',
        features3:'Iso-Lateral motion allows for equal strength development.',
        features4:'Standard weight horns allow for plate storage.',

    },
    {
        id: '15',
        name: 'SM788 SHOULDER PRESS',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/15.jpg',
        dimensions:'1600×1305×1845mm',
        net_weight:'121 Kg',
        gross_weight:'131 Kg',
        features:'Back pad is angled 40 degrees for better stabilization during heavy lifts and helps discourage hyperextension of the spine during exercise.',
        features2:'Standard weight horns allow for plate storage.',
        features3:'Iso-Lateral motion allows for equal strength development.',
    },
    {
        id: '16',
        name: 'SM789 FRONT LAT PULLDOWN',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/16.jpg',
        dimensions:'1520×1905×1980mm',
        net_weight:'132 Kg',
        gross_weight:'142 Kg',
        features:'Underhand grip dictates a natural path of motion ideal for training the Latissimus Dorsi',
        features2:'Additional handle provided to allow user stabilization during one-arm exercises.',
        features3:'Standard weight horns allow for plate storage.',
        features4:'Iso-Lateral motion allows for equal strength development.',
    },
    {
        id: '17',
        name: 'SM790 LEG EXTENSION',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/17.jpg',
        dimensions:'885×590×915mm',
        net_weight:'22 Kg',
        gross_weight:'26 Kg',
        features:'Allows independent leg training for equal strength development.',
        features2:'Two resistance loading positions provide dual strength curves depending on exercise goal.',
        features3:'Lumbar support back pad improves user positioning.',
        features4:'Standard weight horns allow for plate storage.',
    },
    {
        id: '18',
        name: 'SM791 KNEELING LEG CURL',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/18.jpg',
        dimensions:'1390×1150×1230mm',
        net_weight:'86 Kg',
        gross_weight:'96 Kg',
        features:'Standard range limiter allows for limitation of either the start or end of range of motion.',
        features2:'Traditional prone user position.',
        features3:'Divergent angle between hip and chest pads helps reduce lower-back stress.',
        features4:'Standard weight horns allow for plate storage.',
    },
    {
        id: '19',
        name: 'SM792 SEATED BICEPS',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/19.jpg',
        dimensions:'1110×1100×1160mm',
        net_weight:'80 Kg',
        gross_weight:'90 Kg',
        features:'The Plate-Loaded Seated Biceps is designed to give exercisers improved resistance over free weights in a preacher curl position.' ,
        features2:'Angled pad fully supports the upper arm to eliminate unwanted shoulder movement.',
        features3:'Handles rotate to accommodate differences in user forearm length.',
    },
    {
        id: '20',
        name: 'SM794 LATERAL RAISE',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/20.jpg',
        dimensions:'1320×1250×1230mm',
        net_weight:'90 Kg',
        gross_weight:'100 Kg'
    },
    {
        id: '21',
        name: 'SM796 HACK SQUART',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/21.jpg',
        dimensions:'(L)1910×(W)1435×(H)1600mm',
        net_weight:'136 Kg',
        gross_weight:'156 Kg',
        features:'Provides for a natural squatting motion compared to a traditional leg press or hack squat.' ,
        features2:'Machine design reduces back and knee strain through a curved arc of motion.',
        features3:'Standard weight horns allow for plate storage.',
    },
    {
        id: '22',
        name: 'SM797 PECTORAL FLY',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/22.jpg',
        dimensions:'1640×1480×980mm',
        net_weight:'58 Kg',
        gross_weight:'68 Kg'
    },
    {
        id: '23',
        name: 'SM798 PULL OVER',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/23.jpg',
        dimensions:'1850×1385×1450mm',
        net_weight:'80 Kg',
        gross_weight:'90 Kg',
        features:'Seat is angled at 30 degrees to provide user stability' ,
        features2:'Seat belt provides extra stabilization.',
        features3:'counterbalanced movement arm decreases initial starting weight',
        features4:'The degree of shoulder extension is reduced to minimize the stress of the shoulder joint.',
        features5:'Standard weight horns allow for plate storage.',
    },
    {
        id: '24',
        name: 'SM799 SQUAT LUNGE',
        main_category: 'Gym Equipment',
        sub_category: 'SM/CT PLATE LOADED',
        image: 'assets/images/abouelgoukh/gym_equipments/SM_CT/24.png',
        dimensions:'1430×1700×800mm',
        net_weight:'88 Kg',
        gross_weight:'100 Kg'
    }

];