export const treadmills = [
    {
        id: '1',
        name: 'AMERICAN MOTION 8601',
        main_category: 'Treadmill',
        sub_category: 'Cardio, COMMERCIAL',
        image: 'assets/images/abouelgoukh/treadmills/Electric-Treadmills13-300x300.png',
        made_in:'Taiwan',
        power_hp:'2 AC',
        speed: "0-16 K.M/H",
        encline: "Auto",
        saftey_key:'Yes',
        touch:'Yes',
        foldable:'Yes',
        width:'46 CM',
        programs:'6 Programs',
        max_weight:'150 kg',
        max_time: '4 hour'
    },
    {
        id: '2',
        name: 'AMERICAN MOTION 9845',
        main_category: 'Treadmill',
        sub_category: 'COMMERCIAL, ELECTRIC TREADMILLS',
        image: 'assets/images/abouelgoukh/treadmills/Electric-Treadmills15-300x300.png',
        made_in:'Taiwan',
        power_hp:'3 AC',
        speed: " 0-20 K.M/H",
        encline: "Auto",
        saftey_key:'Yes',
        foldable:'Yes',
        width:'54 CM',
        programs:'6 Programs',
        max_weight:'200 kg',
        max_time: '10 hour'
    },
    {
        id: '3',
        name: 'AMERICAN MOTION FITNESS 8608S',
        main_category: 'Treadmill',
        sub_category: 'ELECTRIC TREADMILLS, HOME USE',
        image: 'assets/images/abouelgoukh/treadmills/ElectricTreadmills-300x300.png',
        made_in:'Taiwan',
        power_hp:'1.85 DC',
        speed: "0-12 K.M/H",
        encline: "Manual",
        saftey_key:'Yes',
        foldable:'Yes',
        width:'40 CM',
        programs:'6 Programs',
        max_weight:'100 kg',
        max_time: '1 hour'
    },
    {
        id: '4',
        name: 'AMERICAN MOTION FITNESS 8625C',
        main_category: 'Treadmill',
        sub_category: 'ELECTRIC TREADMILLS, HOME USE',
        image: 'assets/images/abouelgoukh/treadmills/Electric-Treadmills07-300x300.png',
        made_in:'Taiwan',
        power_hp:'2.75 DC',
        speed: "0-16 K.M/H",
        encline: "Manual",
        saftey_key:'Yes',
        foldable:'Yes',
        width:'36 CM',
        programs:'No Programs',
        max_weight:'125 kg',
        max_time: '1, 1/2 hour'
    },
    {
        id: '5',
        name: 'CT800 TREADMILL',
        description:'There are several keys areas that define a well designed treadmill. All Spirit Fitness models offer comfortable belts and cushioning systems, convenient storage and adjustments, generous features and programs, and eye catching aesthetics. Select the design elements you desire to create a product that will retain its value for years to come. The CT800 is even stouter than the XT685 (75 lbs. heavier). This model is very appealing to someone that is a walker or a runner. It features a non-folding platform base which is designed to stand up to the rigors of frequent running. Other design elements include a bright Tri-color LED console, Direct Speed and Incline keys, contact and wireless heart rate, dual drive motor cooling fans, and a maintenance free wax deck system.',
        main_category: 'Treadmill',
        sub_category: 'COMMERCIAL, ELECTRIC TREADMILLS',
        image: 'assets/images/abouelgoukh/treadmills/ct800-300x300.png',
        product_weight:'353 lbs.',
        dimensions: '84 X 35 X 57 in',
        weight_capacity:'450 lbs.',
        heart_rate:'Contact & Telemetric (Chest Strap sold separately)',
        speed_incline:'.5 to 12mph / 15 Levels',
        motor:'This unit comes equipped with a 3.0 hp continuous duty AC motor with Grade H insulation. There are 2 fans that keep the motor cool to ensure it doesn’t overheat and need replacing prematurely.',
        belt:'A durable Multi-ply Habasit® belt is included for comfort and long life.',
        deck:'We use a 1” reversible, dual sided, Phenolic wax deck; this deck is maintenance free (other than monthly cleaning) and can be flipped for extra long life.',
        heart_rate_profile:'There is a bar graph integrated into the console that lets you know where your heart rate is in relation to projected maximum (calculated when you enter your age in the programming section of each program).',
        rollers:'3” diameter rollers are a standard specification on the heavy duty frame.',
        c_safe_power:'The console has C-Safe Power & Communication capabilities for A/V control and virtual racing interaction with WebRacing® software',
        frame:'Lifetime',
        motor_years:' 5 Years',
        deck_parts :' 5 Years',
        labor: '2 Years'
    },
];