export const products = [
    {
        id: '1',
        name: 'VIVA RA2700',
        description:'',
        image: 'assets/images/abouelgoukh/30-600x400.jpg',
        main_category: 'Bicycle',
        sub_category: 'Road',
        additional_info: "frame:700C ALLOY FRAME fork:700C ALLOY FRAME shifters:Shimano Claris brake_levers:Shimano Claris brakes:ALLOY CALIPER BRAKE rear_dreailleur:Shimano Claris 8S front_dreailleur:Shimano Claris cassette:SHIMANO CLARIS 11-28 8S handlebar:ALLOY RACING stem:ALLOY tyres:CST 700C*23C"         
    },            
    {
        id: '2',
        name: 'VIVA RA2800',
        description:'',
        image: 'assets/images/abouelgoukh/stide-20-600x345.jpg',
        main_category: 'Bicycle',
        sub_category: 'Road',
        frame:'700C" ALLOY FRAME',
        fork:'700C" ALLOY FRAME',
        shifters:'Shimano tourney',
        brake_levers:'Shimano tourney',
        brakes:'ALLOY CALIPER BRAKE',
        rear_dreailleur:'Shimano Tourney',
        front_dreailleur:'Shimano Tourney',
        cassette:'Shimano HG200 12-28t 7-Speed',
        handlebar:'ALLOY RACING',
        stem:'ALLOY',
        tyres:'CST 700C*23C'
    },
    {
        id: '3',
        name: 'UNICA',
        description:'The Unica is a great starter road bike or an attractive option for someone upgrading from a cheaper first road bike. Take the spacers out from under the stem and you can get a very low aerodynamic position, making it ideal for racers or speed merchants, and the geometry provides good stability and balance that make it a friendly and appealing ride in most situations.',
        image: 'assets/images/abouelgoukh/50A_UNICA_CLARIS_RED_2015-976x536-600x330.png',
        main_category: 'Bicycle',
        sub_category: 'Road',
        frame:'Aluminium 6061',
        fork:'Alloy 1” 1/8 weight 850 grs.',
        crankset: 'Bottecchia Alu 34/50',
        headset: '1-1/8" Semi-Integrated',
        shifters:'Shimano Claris Mix 16s',
        brake_levers:'Shimano tourney',
        brakes:'Raxe RC 469',
        rear_dreailleur:'Shimano Claris 8S',
        front_dreailleur:'Shimano Claris, Shimano Tiagra 4700',
        cassette:'Shimano 12/32 8s',
        handlebar:'Deda RHM',
        stem:'RAXE Alu',
        tires:'CST/VRB 055 700×25 black',
        chain: 'Fsa Team Issue',
        wheels: 'Bottecchia Racing',
        saddle: 'Bottecchia Eagle Flow'
        
    },
    {
        id: '4',
        name: 'Silverback Stride 15',
        description:'The Stride Mountain Bike Range has been tailored specifically for the needs of the recreational mountain biker. The frame is made from hydroformed lightweight alloy tubing and uses sport-specific geometry to inspire confidence. The frame is also rack-, fender-, disc brake- and bottle cage ready for multi-use adaptability.',
        image: 'assets/images/abouelgoukh/stride-15-600x338.jpg',
        main_category: 'Bicycle',
        sub_category: 'Mountain',
        frame:'Lightweight, Hydroformed, 6061 Butted Aluminum, 135mm QR Dropouts',
        fork:'Suntour XCT HLO, 100mm Travel, 1⁄8 ”Steerer, Hydraulic Lockout, 9mm Dropouts, Opt 1; Opt 2: Orange',
        rear_shock:'N/A',
        rims:'Alex MD17, 32H, Double Wall Alloy Rim, PVC Rimtape, Black, Custom Sector Decals',
        hubs:'Rear: QR Alloy, 6 Hole, 6-Bolt Disc Mount, Adjustable',
        crankset: 'SHIMANO FC-M131, 42/34 / 24T, chainguide, L: 170mm ALL SIZES, Black / Silver',
        headset: '1-1/8" Semi-Integrated',
        shifters:' SHIMANO Altus SL-m310, 3*8 trigger Black',
        brakes:' Shimano BR/BL-M355 Open Hydrulic, Front & Rear Rotors: 160mm, 6-Bolt, Black',
        rear_dreailleur:'  Shimano Acera RD-M360',
        front_dreailleur:'Shimano FD-M190, Triple, Clamp on 34.9mm, Black',
        cassette:'Shimano HG31, 8Speed, 11-32T',
        handlebar:'Sector Incline; Back Sweep: 8 °; Up Sweep: 0 °; 25mm Rise x 31.8mm, 6061 Alloy, Black',
        stem:'Sector Reach, 17 ° x ∮31.8mm; XS / S / M: 80mm; L / XL: 90mm',
        tires:'CST C1820, 26 ”x 1.95, 22TPI',
        saddle: 'Sector, Steel Rails',
        bottom_brancket:'VP, Square Taper',
        seat_post:'Sector, 31.6mm x 350mm; Alloy Black Shaft w / Black Head, Black Bolts'
    },
    {
        id: '5',
        name: 'Silverback Stride Sport',
        description:'The Stride Mountain Bike Range has been tailored specifically for the needs of the recreational mountain biker. The frame is made from hydroformed lightweight alloy tubing and uses sport-specific geometry to inspire confidence. The frame is also rack-, fender-, disc brake- and bottle cage ready for multi-use adaptability.',
        image: 'assets/images/abouelgoukh/stride-sport-600x346.jpg',
        main_category: 'Bicycle',
        sub_category: 'Mountain',
        frame:'Lightweight, Hydroformed, 6061 Butted Aluminum, 135mm QR Dropouts',
        fork:'Suntour M3020, 75mm Travel, 1⁄8 ”Steerer, Hydraulic Lockout, 9mm Dropouts.',
        rear_shock:'N/A',
        rims:'Weinmann TM19, 32H SingleWall Alloy Rim',
        hubs:'QR Alloy',
        crankset: 'Sountour XCC, 42/34/24',
        headset: '1-1/8" Semi-Integrated',
        shifters:' front: ST-EF42 rear: ST-EF41, 3*7 Easyfire',
        brakes:' Silverback, Alloy Melt_forged, V0Brake',
        rear_dreailleur:' Shimano tourney, RD-TX800',
        front_dreailleur:'Shimano fd-tx50',
        cassette:'Shimano MT-TZ21 7 Spedd',
        handlebar:'Silverback, Alloy',
        stem:'RAXE Alu',
        tires:'KENDA K922, 26″',
        wheels: 'Bottecchia Racing',
        saddle: 'Silverback, Steel Rails'
    }
];